//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySimpayBot.JobManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportJobInput", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportJobInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceIdentity IdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceReportJobInputParams ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceIdentity Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceReportJobInputParams Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceIdentity", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JsonWebTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JsonWebToken {
            get {
                return this.JsonWebTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.JsonWebTokenField, value) != true)) {
                    this.JsonWebTokenField = value;
                    this.RaisePropertyChanged("JsonWebToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportJobInputParams", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportJobInputParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeadLineDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FetchExpirationActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FetchExpirationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntervalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxFetchNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessID {
            get {
                return this.BusinessIDField;
            }
            set {
                if ((this.BusinessIDField.Equals(value) != true)) {
                    this.BusinessIDField = value;
                    this.RaisePropertyChanged("BusinessID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeadLineDateTime {
            get {
                return this.DeadLineDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeadLineDateTimeField, value) != true)) {
                    this.DeadLineDateTimeField = value;
                    this.RaisePropertyChanged("DeadLineDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FetchExpirationAction {
            get {
                return this.FetchExpirationActionField;
            }
            set {
                if ((object.ReferenceEquals(this.FetchExpirationActionField, value) != true)) {
                    this.FetchExpirationActionField = value;
                    this.RaisePropertyChanged("FetchExpirationAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FetchExpirationTime {
            get {
                return this.FetchExpirationTimeField;
            }
            set {
                if ((this.FetchExpirationTimeField.Equals(value) != true)) {
                    this.FetchExpirationTimeField = value;
                    this.RaisePropertyChanged("FetchExpirationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntervalTime {
            get {
                return this.IntervalTimeField;
            }
            set {
                if ((this.IntervalTimeField.Equals(value) != true)) {
                    this.IntervalTimeField = value;
                    this.RaisePropertyChanged("IntervalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxFetchNumber {
            get {
                return this.MaxFetchNumberField;
            }
            set {
                if ((this.MaxFetchNumberField.Equals(value) != true)) {
                    this.MaxFetchNumberField = value;
                    this.RaisePropertyChanged("MaxFetchNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDateTime {
            get {
                return this.StartDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateTimeField, value) != true)) {
                    this.StartDateTimeField = value;
                    this.RaisePropertyChanged("StartDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportJobOutput", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportJobOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceStatus", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportResultInput", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportResultInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceIdentity IdentityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceReportResultInputParams ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceIdentity Identity {
            get {
                return this.IdentityField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentityField, value) != true)) {
                    this.IdentityField = value;
                    this.RaisePropertyChanged("Identity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceReportResultInputParams Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportResultInputParams", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportResultInputParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BusinessIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BusinessID {
            get {
                return this.BusinessIDField;
            }
            set {
                if ((this.BusinessIDField.Equals(value) != true)) {
                    this.BusinessIDField = value;
                    this.RaisePropertyChanged("BusinessID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportDateTime {
            get {
                return this.ReportDateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportDateTimeField, value) != true)) {
                    this.ReportDateTimeField = value;
                    this.RaisePropertyChanged("ReportDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UID {
            get {
                return this.UIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UIDField, value) != true)) {
                    this.UIDField = value;
                    this.RaisePropertyChanged("UID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceReportResultOutput", Namespace="http://schemas.datacontract.org/2004/07/JobService")]
    [System.SerializableAttribute()]
    public partial class WebServiceReportResultOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MySimpayBot.JobManagementService.WebServiceStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MySimpayBot.JobManagementService.WebServiceStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobManagementService.ICore")]
    public interface ICore {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICore/ReportJob", ReplyAction="http://tempuri.org/ICore/ReportJobResponse")]
        MySimpayBot.JobManagementService.WebServiceReportJobOutput ReportJob(MySimpayBot.JobManagementService.WebServiceReportJobInput ws);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICore/ReportJob", ReplyAction="http://tempuri.org/ICore/ReportJobResponse")]
        System.Threading.Tasks.Task<MySimpayBot.JobManagementService.WebServiceReportJobOutput> ReportJobAsync(MySimpayBot.JobManagementService.WebServiceReportJobInput ws);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICore/ReportResult", ReplyAction="http://tempuri.org/ICore/ReportResultResponse")]
        MySimpayBot.JobManagementService.WebServiceReportResultOutput ReportResult(MySimpayBot.JobManagementService.WebServiceReportResultInput ws);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICore/ReportResult", ReplyAction="http://tempuri.org/ICore/ReportResultResponse")]
        System.Threading.Tasks.Task<MySimpayBot.JobManagementService.WebServiceReportResultOutput> ReportResultAsync(MySimpayBot.JobManagementService.WebServiceReportResultInput ws);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoreChannel : MySimpayBot.JobManagementService.ICore, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreClient : System.ServiceModel.ClientBase<MySimpayBot.JobManagementService.ICore>, MySimpayBot.JobManagementService.ICore {
        
        public CoreClient() {
        }
        
        public CoreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MySimpayBot.JobManagementService.WebServiceReportJobOutput ReportJob(MySimpayBot.JobManagementService.WebServiceReportJobInput ws) {
            return base.Channel.ReportJob(ws);
        }
        
        public System.Threading.Tasks.Task<MySimpayBot.JobManagementService.WebServiceReportJobOutput> ReportJobAsync(MySimpayBot.JobManagementService.WebServiceReportJobInput ws) {
            return base.Channel.ReportJobAsync(ws);
        }
        
        public MySimpayBot.JobManagementService.WebServiceReportResultOutput ReportResult(MySimpayBot.JobManagementService.WebServiceReportResultInput ws) {
            return base.Channel.ReportResult(ws);
        }
        
        public System.Threading.Tasks.Task<MySimpayBot.JobManagementService.WebServiceReportResultOutput> ReportResultAsync(MySimpayBot.JobManagementService.WebServiceReportResultInput ws) {
            return base.Channel.ReportResultAsync(ws);
        }
    }
}
